// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "Open_IM/internal/gateway/internal/handler/auth"
	client "Open_IM/internal/gateway/internal/handler/client"
	conversation "Open_IM/internal/gateway/internal/handler/conversation"
	friend "Open_IM/internal/gateway/internal/handler/friend"
	group "Open_IM/internal/gateway/internal/handler/group"
	supergroup "Open_IM/internal/gateway/internal/handler/supergroup"
	"Open_IM/internal/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.BodyLoggerMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user_register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user_token",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/parse_token",
					Handler: auth.ParseTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/force_logout",
					Handler: auth.ForceLogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.BodyLoggerMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/set_client_config",
					Handler: client.SetClientConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_client_config",
					Handler: client.GetClientConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/init"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.BodyLoggerMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/get_all_conversations",
					Handler: conversation.GetAllConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_conversation",
					Handler: conversation.GetConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_conversations",
					Handler: conversation.GetConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/set_conversation",
					Handler: conversation.SetConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/batch_set_conversation",
					Handler: conversation.BatchSetConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/set_recv_msg_opt",
					Handler: conversation.SetRecvMsgOptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modify_conversation_field",
					Handler: conversation.ModifyConversationFieldHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/conversation"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.BodyLoggerMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add_friend",
					Handler: friend.AddFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete_friend",
					Handler: friend.DeleteFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_friend_apply_list",
					Handler: friend.GetFriendApplyListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_self_friend_apply_list",
					Handler: friend.GetSelfFriendApplyListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_friend_list",
					Handler: friend.GetFriendListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add_friend_response",
					Handler: friend.RespondFriendApplyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/set_friend_remark",
					Handler: friend.SetFriendRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add_black",
					Handler: friend.AddFriendBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_black_list",
					Handler: friend.GetFriendBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/remove_black",
					Handler: friend.RemoveFriendBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/import_friend",
					Handler: friend.ImportFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/is_friend",
					Handler: friend.CheckFriendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/friend"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.BodyLoggerMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/create_group",
					Handler: group.CreateGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/set_group_info",
					Handler: group.SetGroupInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/join_group",
					Handler: group.JoinGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/quit_group",
					Handler: group.QuitGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group_application_response",
					Handler: group.RespondGroupApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/transfer_group",
					Handler: group.TransferGroupOwnerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_recv_group_applicationList",
					Handler: group.GetRecvGroupApplicationListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_user_req_group_applicationList",
					Handler: group.GetUserReqGroupApplicationListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_groups_info",
					Handler: group.GetGroupsInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/kick_group",
					Handler: group.KickGroupMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_group_all_member_list",
					Handler: group.GetGroupAllMemberListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_group_members_info",
					Handler: group.GetGroupMembersInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/invite_user_to_group",
					Handler: group.InviteUserToGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/invite_user_to_groups",
					Handler: group.InviteUserToGroupsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_joined_group_list",
					Handler: group.GetJoinedGroupListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/dismiss_group",
					Handler: group.DismissGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mute_group_member",
					Handler: group.MuteGroupMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cancel_mute_group_member",
					Handler: group.CancelMuteGroupMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mute_group",
					Handler: group.MuteGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cancel_mute_group",
					Handler: group.CancelMuteGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/set_group_member_nickname",
					Handler: group.SetGroupMemberNicknameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/set_group_member_info",
					Handler: group.SetGroupMemberInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_group_abstract_info",
					Handler: group.GetGroupAbstractInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/group"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.BodyLoggerMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/get_joined_group_list",
					Handler: supergroup.GetJoinedSuperGroupListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_groups_info",
					Handler: supergroup.GetSuperGroupsInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/super_group"),
	)
}
