// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Secret   string `json:"secret" validate:"required,max=32"`
	Platform int32  `json:"platform" validate:"required,min=1,max=12"`
	ApiUserInfo
	OperationID string `json:"operationID" validate:"required"`
}

type ApiUserInfo struct {
	UserID      string `json:"userID" validate:"required,min=1,max=64"`
	Nickname    string `json:"nickname,optional" validate:"omitempty,min=1,max=64"`
	FaceURL     string `json:"faceURL,optional" validate:"omitempty,max=1024"`
	Gender      int32  `json:"gender,optional" validate:"omitempty,oneof=0 1 2"`
	PhoneNumber string `json:"phoneNumber,optional" validate:"omitempty,max=32"`
	Birth       uint32 `json:"birth,optional" validate:"omitempty"`
	Email       string `json:"email,optional" validate:"omitempty,max=64"`
	CreateTime  int64  `json:"createTime"`
	LoginLimit  int32  `json:"loginLimit,optional" validate:"omitempty"`
	Ex          string `json:"ex,optional" validate:"omitempty,max=1024"`
	BirthStr    string `json:"birthStr,optional" validate:"omitempty"`
}

type RegisterResponse struct {
	CommResp
	UserToken UserTokenInfo `json:"data"`
}

type CommResp struct {
	ErrCode int32  `json:"errCode"`
	ErrMsg  string `json:"errMsg"`
}

type UserTokenInfo struct {
	UserID      string `json:"userID"`
	Token       string `json:"token"`
	ExpiredTime int64  `json:"expiredTime"`
}

type LoginRequest struct {
	Secret      string `json:"secret" validate:"required,max=32"`
	Platform    int32  `json:"platform" validate:"required,min=1,max=12"`
	UserID      string `json:"userID" validate:"required,min=1,max=64"`
	LoginIp     string `json:"loginIp"`
	OperationID string `json:"operationID" validate:"required"`
}

type LoginResponse struct {
	CommResp
	UserToken UserTokenInfo `json:"data"`
}

type ParseTokenRequest struct {
	OperationID string `json:"operationID" validate:"required"`
}

type ParseTokenResponse struct {
	CommResp
	Data       map[string]interface{} `json:"data"`
	ExpireTime ExpireTime             `json:"-"`
}

type ExpireTime struct {
	ExpireTimeSeconds uint32 `json:"expireTimeSeconds"`
}

type ForceLogoutRequest struct {
	Platform    int32  `json:"platform" validate:"required,min=1,max=12"`
	FromUserID  string `json:"fromUserID" validate:"required,min=1,max=64"`
	OperationID string `json:"operationID" validate:"required"`
}

type ForceLogoutResponse struct {
	CommResp
}

type SetClientConfigRequest struct {
	OperationID     string  `json:"operationID"  validate:"required"`
	DiscoverPageURL *string `json:"discoverPageURL"`
}

type SetClientConfigResponse struct {
	CommResp
}

type GetClientConfigRequest struct {
	OperationID string `json:"operationID"  validate:"required"`
}

type GetClientConfigResponse struct {
	CommResp
	Data DiscoverPageURL `json:"data"`
}

type DiscoverPageURL struct {
	DiscoverPageURL string `json:"discoverPageURL"`
}

type GetAllConversationsRequest struct {
	OwnerUserID string `json:"ownerUserID" validate:"required"`
	OperationID string `json:"operationID" validate:"required"`
}

type GetAllConversationsResponse struct {
	CommResp
	Conversations []Conversation `json:"data"`
}

type Conversation struct {
	OwnerUserID           string `json:"ownerUserID" validate:"required"`
	ConversationID        string `json:"conversationID" validate:"required"`
	ConversationType      int32  `json:"conversationType" validate:"required"`
	UserID                string `json:"userID"`
	GroupID               string `json:"groupID"`
	RecvMsgOpt            int32  `json:"recvMsgOpt,optional"  validate:"omitempty,oneof=0 1 2"`
	UnreadCount           int32  `json:"unreadCount,optional"  validate:"omitempty"`
	DraftTextTime         int64  `json:"draftTextTime"`
	IsPinned              bool   `json:"isPinned,optional" validate:"omitempty"`
	IsPrivateChat         bool   `json:"isPrivateChat"`
	BurnDuration          int32  `json:"burnDuration"`
	GroupAtType           int32  `json:"groupAtType"`
	IsNotInGroup          bool   `json:"isNotInGroup"`
	UpdateUnreadCountTime int64  `json:"updateUnreadCountTime"`
	AttachedInfo          string `json:"attachedInfo"`
	Ex                    string `json:"ex"`
}

type GetConversationRequest struct {
	ConversationID string `json:"conversationID" validate:"required"`
	OwnerUserID    string `json:"ownerUserID" validate:"required"`
	OperationID    string `json:"operationID" validate:"required"`
}

type GetConversationResponse struct {
	CommResp
	Conversation Conversation `json:"data"`
}

type GetConversationsRequest struct {
	ConversationIDs []string `json:"conversationIDs" validate:"required"`
	OwnerUserID     string   `json:"ownerUserID" validate:"required"`
	OperationID     string   `json:"operationID" validate:"required"`
}

type GetConversationsResponse struct {
	CommResp
	Conversations []Conversation `json:"data"`
}

type SetConversationRequest struct {
	Conversation
	NotificationType int32  `json:"notificationType"`
	OperationID      string `json:"operationID" validate:"required"`
}

type SetConversationResponse struct {
	CommResp
}

type BatchSetConversationsRequest struct {
	Conversations    []Conversation `json:"conversations" validate:"required"`
	NotificationType int32          `json:"notificationType"`
	OwnerUserID      string         `json:"ownerUserID" validate:"required"`
	OperationID      string         `json:"operationID" validate:"required"`
}

type BatchSetConversationsResponse struct {
	CommResp
	Data SuccessAndFailed `json:"data"`
}

type SuccessAndFailed struct {
	Success []string `json:"success"`
	Failed  []string `json:"failed"`
}

type SetRecvMsgOptRequest struct {
	OwnerUserID      string `json:"ownerUserID" validate:"required"`
	ConversationID   string `json:"conversationID"`
	RecvMsgOpt       int32  `json:"recvMsgOpt,optional"  validate:"omitempty,oneof=0 1 2"`
	OperationID      string `json:"operationID" validate:"required"`
	NotificationType int32  `json:"notificationType"`
}

type SetRecvMsgOptResponse struct {
	CommResp
}

type ModifyConversationFieldRequest struct {
	Conversation
	FieldType   int32    `json:"fieldType" validate:"required"`
	UserIDList  []string `json:"userIDList" validate:"required"`
	OperationID string   `json:"operationID" validate:"required"`
}

type ModifyConversationFieldResponse struct {
	CommResp
}

type AddFriendRequest struct {
	ParamsCommFriend
	ReqMsg string `json:"reqMsg"`
}

type ParamsCommFriend struct {
	OperationID string `json:"operationID" validate:"required"`
	ToUserID    string `json:"toUserID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type AddFriendResponse struct {
	CommResp
}

type DeleteFriendRequest struct {
	ParamsCommFriend
}

type DeleteFriendResponse struct {
	CommResp
}

type GetFriendApplyListRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type GetFriendApplyListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type GetSelfFriendApplyListRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type GetSelfFriendApplyListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type GetFriendListRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type GetFriendListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type RespondFriendApplyRequest struct {
	ParamsCommFriend
	Flag      int32  `json:"flag" validate:"required,oneof=-1 0 1"`
	HandleMsg string `json:"handleMsg"`
}

type RespondFriendApplyResponse struct {
	CommResp
}

type SetFriendRemarkRequest struct {
	ParamsCommFriend
	Remark string `json:"remark"`
}

type SetFriendRemarkResponse struct {
	CommResp
}

type AddFriendBlacklistRequest struct {
	ParamsCommFriend
}

type AddFriendBlacklistResponse struct {
	CommResp
}

type GetFriendBlacklistRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type GetFriendBlacklistResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type RemoveFriendBlacklistRequest struct {
	ParamsCommFriend
}

type RemoveFriendBlacklistResponse struct {
	CommResp
}

type ImportFriendRequest struct {
	FriendUserIDList []string `json:"friendUserIDList" validate:"required"`
	OperationID      string   `json:"operationID" validate:"required"`
	FromUserID       string   `json:"fromUserID" validate:"required"`
}

type ImportFriendResponse struct {
	CommResp
	UserIDResultList []UserIDResult `json:"data"`
}

type UserIDResult struct {
	UserID string `json:"userID"`
	Result int32  `json:"result"`
}

type CheckFriendRequest struct {
	ParamsCommFriend
}

type CheckFriendResponse struct {
	CommResp
	Response IsFriend `json:"data"`
}

type IsFriend struct {
	Friend bool `json:"isFriend"`
}

type CreateGroupRequest struct {
	MemberList   []*GroupAddMemberInfo `json:"memberList"`
	OwnerUserID  string                `json:"ownerUserID"`
	GroupType    int32                 `json:"groupType"`
	GroupName    string                `json:"groupName"`
	Notification string                `json:"notification"`
	Introduction string                `json:"introduction"`
	FaceURL      string                `json:"faceURL"`
	Ex           string                `json:"ex"`
	OperationID  string                `json:"operationID" validate:"required"`
	GroupID      string                `json:"groupID"`
}

type GroupAddMemberInfo struct {
	UserID    string `json:"userID" validate:"required"`
	RoleLevel int32  `json:"roleLevel" validate:"required,oneof= 1 3"`
}

type CreateGroupResponse struct {
	CommResp
	Data map[string]interface{} `json:"data"`
}

type SetGroupInfoRequest struct {
	GroupID           string `json:"groupID" validate:"required"`
	GroupName         string `json:"groupName"`
	Notification      string `json:"notification"`
	Introduction      string `json:"introduction"`
	FaceURL           string `json:"faceURL"`
	Ex                string `json:"ex"`
	OperationID       string `json:"operationID" validate:"required"`
	NeedVerification  *int32 `json:"needVerification"`
	LookMemberInfo    *int32 `json:"lookMemberInfo"`
	ApplyMemberFriend *int32 `json:"applyMemberFriend"`
}

type SetGroupInfoResponse struct {
	CommResp
}

type JoinGroupRequest struct {
	GroupID       string `json:"groupID" validate:"required"`
	ReqMessage    string `json:"reqMessage"`
	OperationID   string `json:"operationID" validate:"required"`
	JoinSource    int32  `json:"joinSource"`
	InviterUserID string `json:"inviterUserID"`
}

type JoinGroupResponse struct {
	CommResp
}

type QuitGroupRequest struct {
	GroupID     string `json:"groupID" validate:"required"`
	OperationID string `json:"operationID" validate:"required"`
}

type QuitGroupResponse struct {
	CommResp
}

type RespondGroupApplicationRequest struct {
	OperationID  string `json:"operationID" validate:"required"`
	GroupID      string `json:"groupID" validate:"required"`
	FromUserID   string `json:"fromUserID" validate:"required"` // application from FromUserID
	HandledMsg   string `json:"handledMsg"`
	HandleResult int32  `json:"handleResult" validate:"required,oneof=-1 1"`
}

type RespondGroupApplicationResponse struct {
	CommResp
}

type TransferGroupOwnerRequest struct {
	GroupID        string `json:"groupID" validate:"required"`
	OldOwnerUserID string `json:"oldOwnerUserID" validate:"required"`
	NewOwnerUserID string `json:"newOwnerUserID" validate:"required"`
	OperationID    string `json:"operationID" validate:"required"`
}

type TransferGroupOwnerResponse struct {
	CommResp
}

type GetRecvGroupApplicationListRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type GetRecvGroupApplicationListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type GetUserReqGroupApplicationListRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	UserID      string `json:"userID" validate:"required"`
}

type GetUserReqGroupApplicationListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type GetGroupsInfoRequest struct {
	GroupIDList []string `json:"groupIDList" validate:"required"`
	OperationID string   `json:"operationID" validate:"required"`
}

type GetGroupsInfoResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type KickGroupMemberRequest struct {
	GroupID          string   `json:"groupID" validate:"required"`
	KickedUserIDList []string `json:"kickedUserIDList" validate:"required"`
	Reason           string   `json:"reason"`
	OperationID      string   `json:"operationID" validate:"required"`
}

type KickGroupMemberResponse struct {
	CommResp
	UserIDResultList []*UserIDResult `json:"data"`
}

type GetGroupAllMemberListRequest struct {
	GroupID     string `json:"groupID" validate:"required"`
	OperationID string `json:"operationID" validate:"required"`
	Offset      int32  `json:"offset"`
	Count       int32  `json:"count"`
}

type GetGroupAllMemberListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type GetGroupMembersInfoRequest struct {
	GroupID     string   `json:"groupID" validate:"required"`
	MemberList  []string `json:"memberList" validate:"required"`
	OperationID string   `json:"operationID" validate:"required"`
	NoCache     bool     `json:"noCache"`
}

type GetGroupMembersInfoResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type InviteUserToGroupRequest struct {
	GroupID           string   `json:"groupID" validate:"required"`
	InvitedUserIDList []string `json:"invitedUserIDList" validate:"required"`
	Reason            string   `json:"reason"`
	OperationID       string   `json:"operationID" validate:"required"`
}

type InviteUserToGroupResponse struct {
	CommResp
	UserIDResultList []*UserIDResult `json:"data"`
}

type InviteUserToGroupsRequest struct {
	GroupIDList   string `json:"groupIDList" validate:"required"`
	InvitedUserID string `json:"invitedUserID" validate:"required"`
	Reason        string `json:"reason"`
	OperationID   string `json:"operationID" validate:"required"`
}

type InviteUserToGroupsResponse struct {
	CommResp
}

type GetJoinedGroupListRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type GetJoinedGroupListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type DismissGroupRequest struct {
	GroupID     string `json:"groupID" validate:"required"`
	OperationID string `json:"operationID" validate:"required"`
}

type DismissGroupResponse struct {
	CommResp
}

type MuteGroupMemberRequest struct {
	OperationID  string `json:"operationID" validate:"required"`
	GroupID      string `json:"groupID" validate:"required"`
	UserID       string `json:"userID" validate:"required"`
	MutedSeconds uint32 `json:"mutedSeconds" validate:"required"`
}

type MuteGroupMemberResponse struct {
	CommResp
}

type CancelMuteGroupMemberRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	GroupID     string `json:"groupID" validate:"required"`
	UserID      string `json:"userID" validate:"required"`
}

type CancelMuteGroupMemberResponse struct {
	CommResp
}

type MuteGroupRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	GroupID     string `json:"groupID" validate:"required"`
}

type MuteGroupResponse struct {
	CommResp
}

type CancelMuteGroupRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	GroupID     string `json:"groupID" validate:"required"`
}

type CancelMuteGroupResponse struct {
	CommResp
}

type SetGroupMemberNicknameRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	GroupID     string `json:"groupID" validate:"required"`
	UserID      string `json:"userID" validate:"required"`
	Nickname    string `json:"nickname"`
}

type SetGroupMemberNicknameResponse struct {
	CommResp
}

type SetGroupMemberInfoRequest struct {
	OperationID string  `json:"operationID" validate:"required"`
	GroupID     string  `json:"groupID" validate:"required"`
	UserID      string  `json:"userID" validate:"required"`
	Nickname    *string `json:"nickname"`
	FaceURL     *string `json:"userGroupFaceUrl"`
	RoleLevel   *int32  `json:"roleLevel" validate:"gte=1,lte=3"`
	Ex          *string `json:"ex"`
}

type SetGroupMemberInfoResponse struct {
	CommResp
}

type GetGroupAbstractInfoRequest struct {
	OperationID string `json:"operationID"`
	GroupID     string `json:"groupID"`
}

type GetGroupAbstractInfoResponse struct {
	CommResp
	GroupMemberNumber   int32  `json:"groupMemberNumber"`
	GroupMemberListHash uint64 `json:"groupMemberListHash"`
}

type GetJoinedSuperGroupListRequest struct {
	OperationID string `json:"operationID" validate:"required"`
	FromUserID  string `json:"fromUserID" validate:"required"`
}

type GetJoinedSuperGroupListResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type GetSuperGroupsInfoRequest struct {
	GroupIDList []string `json:"groupIDList" validate:"required"`
	OperationID string   `json:"operationID" validate:"required"`
}

type GetSuperGroupsInfoResponse struct {
	CommResp
	Data []map[string]interface{} `json:"data"`
}

type GetSeqRequest struct {
	ReqIdentifier int    `json:"reqIdentifier" validate:"required"`
	SendID        string `json:"sendID" validate:"required"`
	OperationID   string `json:"operationID" validate:"required"`
	MsgIncr       int    `json:"msgIncr" validate:"required"`
}

type GetSeqResponse struct {
	CommResp
	MsgIncr       int        `json:"msgIncr"`
	ReqIdentifier int        `json:"reqIdentifier"`
	Data          GetSeqData `json:"data"`
}

type GetSeqData struct {
	MaxSeq uint32 `json:"maxSeq"`
	MinSeq uint32 `json:"minSeq"`
}

type SendMsgRequest struct {
	SenderPlatformID int32           `json:"senderPlatformID" validate:"required"`
	SendID           string          `json:"sendID" validate:"required"`
	SenderNickName   string          `json:"senderNickName"`
	SenderFaceURL    string          `json:"senderFaceUrl"`
	OperationID      string          `json:"operationID" validate:"required"`
	SessionType      int32           `json:"sessionType" validate:"required"`
	MsgFrom          int32           `json:"msgFrom" validate:"required"`
	ContentType      int32           `json:"contentType" validate:"required"`
	RecvID           string          `json:"recvID"`
	GroupID          string          `json:"groupID"`
	ForceList        []string        `json:"forceList"`
	Content          []byte          `json:"content" validate:"required"`
	Options          map[string]bool `json:"options"`
	ClientMsgID      string          `json:"clientMsgID" validate:"required"`
	CreateTime       int64           `json:"createTime" validate:"required"`
	OfflineInfo      OfflinePushInfo `json:"offlineInfo"`
}

type OfflinePushInfo struct {
	Title         string `json:"title,omitempty"`
	Desc          string `json:"desc,omitempty"`
	Ex            string `json:"ex,omitempty"`
	IOSPushSound  string `json:"iOSPushSound,omitempty"`
	IOSBadgeCount bool   `json:"iOSBadgeCount,omitempty"`
}

type SendMsgResponse struct {
	CommResp
	Data SendMsgData `json:"data"`
}

type SendMsgData struct {
	ClientMsgID string `json:"clientMsgID"`
	ServerMsgID string `json:"serverMsgID"`
	SendTime    int64  `json:"sendTime"`
}

type PullMsgBySeqListRequest struct {
	ReqIdentifier int      `json:"reqIdentifier" validate:"required"`
	SendID        string   `json:"sendID" validate:"required"`
	OperationID   string   `json:"operationID" validate:"required"`
	SeqList       []uint32 `json:"seqList"`
}

type PullMsgBySeqListResponse struct {
	CommResp
	ReqIdentifier int       `json:"reqIdentifier"`
	Data          []MsgData `json:"data"`
}

type MsgData struct {
	SendID               string           `json:"sendID,omitempty"`
	RecvID               string           `json:"recvID,omitempty"`
	GroupID              string           `json:"groupID,omitempty"`
	ClientMsgID          string           `json:"clientMsgID,omitempty"`
	ServerMsgID          string           `json:"serverMsgID,omitempty"`
	SenderPlatformID     int32            `json:"senderPlatformID,omitempty"`
	SenderNickname       string           `json:"senderNickname,omitempty"`
	SenderFaceURL        string           `json:"senderFaceURL,omitempty"`
	SessionType          int32            `json:"sessionType,omitempty"`
	MsgFrom              int32            `json:"msgFrom,omitempty"`
	ContentType          int32            `json:"contentType,omitempty"`
	Content              []byte           `json:"content,omitempty"`
	Seq                  uint32           `json:"seq,omitempty"`
	SendTime             int64            `json:"sendTime,omitempty"`
	CreateTime           int64            `json:"createTime,omitempty"`
	Status               int32            `json:"status,omitempty"`
	Options              map[string]bool  `json:"options,omitempty"`
	OfflinePushInfo      *OfflinePushInfo `json:"offlinePushInfo,omitempty"`
	AtUserIDList         []string         `json:"atUserIDList,omitempty"`
	MsgDataList          []byte           `json:"msgDataList,omitempty"`
	AttachedInfo         string           `json:"attachedInfo,omitempty"`
	Ex                   string           `json:"ex,omitempty"`
	IsReact              bool             `json:"isReact,omitempty"`
	IsExternalExtensions bool             `json:"isExternalExtensions,omitempty"`
	MsgFirstModifyTime   int64            `json:"msgFirstModifyTime,omitempty"`
}

type DelMsgRequest struct {
	UserID      string   `json:"userID" validate:"required"`
	SeqList     []uint32 `json:"seqList" validate:"required"`
	OperationID string   `json:"operationID" validate:"required"`
}

type DelMsgResponse struct {
	CommResp
}

type DelSuperGroupMsgRequest struct {
	UserID      string   `json:"userID" validate:"required"`
	GroupID     string   `json:"groupID" validate:"required"`
	SeqList     []uint32 `json:"seqList"`
	IsAllDelete bool     `json:"isAllDelete"`
	OperationID string   `json:"operationID" validate:"required"`
}

type DelSuperGroupMsgResponse struct {
	CommResp
}

type ClearMsgRequest struct {
	UserID      string `json:"userID"  validate:"required"`
	OperationID string `json:"operationID"  validate:"required"`
}

type ClearMsgResponse struct {
	CommResp
}

type ManagementSendMsgRequest struct {
	ManagementSendMsg
	RecvID string `json:"recvID"`
}

type ManagementSendMsg struct {
	OperationID         string                 `json:"operationID" validate:"required"`
	BusinessOperationID string                 `json:"businessOperationID"`
	SendID              string                 `json:"sendID" validate:"required"`
	GroupID             string                 `json:"groupID"`
	SenderNickname      string                 `json:"senderNickname"`
	SenderFaceURL       string                 `json:"senderFaceURL"`
	SenderPlatformID    int32                  `json:"senderPlatformID"`
	Content             map[string]interface{} `json:"content" validate:"required"`
	ContentType         int32                  `json:"contentType" validate:"required"`
	SessionType         int32                  `json:"sessionType" validate:"required"`
	IsOnlineOnly        bool                   `json:"isOnlineOnly"`
	NotOfflinePush      bool                   `json:"notOfflinePush"`
	OfflinePushInfo     OfflinePushInfo        `json:"offlinePushInfo"`
}

type ManagementSendMsgResponse struct {
	CommResp
	ResultList UserSendMsgResp `json:"data"`
}

type UserSendMsgResp struct {
	ServerMsgID string `json:"serverMsgID,omitempty"`
	ClientMsgID string `json:"clientMsgID,omitempty"`
	SendTime    int64  `json:"sendTime,omitempty"`
	Ex          string `json:"ex,omitempty"`
}

type ManagementBatchSendMsgRequest struct {
	ManagementSendMsg
	IsSendAll  bool     `json:"isSendAll"`
	RecvIDList []string `json:"recvIDList"`
}

type ManagementBatchSendMsgResponse struct {
	CommResp
	Data ManagementBatchSendMsgData `json:"data"`
}

type ManagementBatchSendMsgData struct {
	ResultList []*SingleReturnResult `json:"resultList"`
}

type SingleReturnResult struct {
	ServerMsgID string `json:"serverMsgID"`
	ClientMsgID string `json:"clientMsgID"`
	SendTime    int64  `json:"sendTime"`
	RecvID      string `json:"recvID"`
}

type CheckMsgIsSendSuccessRequest struct {
	OperationID string `json:"operationID"`
}

type CheckMsgIsSendSuccessResponse struct {
	CommResp
	Status int32 `json:"status"`
}

type SetMsgMinSeqRequest struct {
	UserID      string `json:"userID"  validate:"required"`
	GroupID     string `json:"groupID"`
	MinSeq      uint32 `json:"minSeq"  validate:"required"`
	OperationID string `json:"operationID"  validate:"required"`
}

type SetMsgMinSeqResponse struct {
	CommResp
}

type SetMessageReactionExtensionsRequest struct {
	OperationID           string               `json:"operationID" validate:"required"`
	SourceID              string               `json:"sourceID"  validate:"required"`
	SessionType           int32                `json:"sessionType" validate:"required"`
	ReactionExtensionList map[string]*KeyValue `json:"reactionExtensionList,omitempty" validate:"required"`
	ClientMsgID           string               `json:"clientMsgID" validate:"required"`
	Ex                    *string              `json:"ex"`
	AttachedInfo          *string              `json:"attachedInfo"`
	IsReact               bool                 `json:"isReact"`
	IsExternalExtensions  bool                 `json:"isExternalExtensions"`
	MsgFirstModifyTime    int64                `json:"msgFirstModifyTime"`
	Seq                   uint32               `json:"seq"`
}

type KeyValue struct {
	TypeKey          string `json:"typeKey,omitempty"`
	Value            string `json:"value,omitempty"`
	LatestUpdateTime int64  `json:"latestUpdateTime,omitempty"`
}

type SetMessageReactionExtensionsResponse struct {
	CommResp
	Data SetMessageReactionExtensionsData `json:"data"`
}

type SetMessageReactionExtensionsData struct {
	ResultKeyValue     []*KeyValueResp `json:"result"`
	MsgFirstModifyTime int64           `json:"msgFirstModifyTime"`
	IsReact            bool            `json:"isReact"`
}

type KeyValueResp struct {
	KeyValue *KeyValue `json:"keyValue,omitempty"`
	ErrCode  int32     `json:"errCode,omitempty"`
	ErrMsg   string    `json:"errMsg,omitempty"`
}

type GetMessageListReactionExtensionsRequest struct {
	OperationID            string                                                    `json:"operationID" validate:"required"`
	SourceID               string                                                    `json:"sourceID"  validate:"required"`
	SessionType            int32                                                     `json:"sessionType" validate:"required"`
	IsExternalExtensions   bool                                                      `json:"isExternalExtensions"`
	TypeKeyList            []string                                                  `json:"typeKeyList"`
	MessageReactionKeyList []*GetMessageListReactionExtensionsReq_MessageReactionKey `json:"messageReactionKeyList" validate:"required"`
}

type GetMessageListReactionExtensionsReq_MessageReactionKey struct {
	ClientMsgID        string `json:"clientMsgID,omitempty"`
	MsgFirstModifyTime int64  `json:"msgFirstModifyTime,omitempty"`
}

type GetMessageListReactionExtensionsResponse struct {
	CommResp
	Data []*SingleMessageExtensionResult `json:"data"`
}

type SingleMessageExtensionResult struct {
	ErrCode               int32                `json:"errCode,omitempty"`
	ErrMsg                string               `json:"errMsg,omitempty"`
	ReactionExtensionList map[string]*KeyValue `json:"reactionExtensionList,omitempty"`
	ClientMsgID           string               `json:"clientMsgID,omitempty"`
}

type AddMessageReactionExtensionsRequest struct {
	SetMessageReactionExtensionsRequest
}

type AddMessageReactionExtensionsResponse struct {
	SetMessageReactionExtensionsResponse
}

type DeleteMessageReactionExtensionsRequest struct {
	OperationID           string      `json:"operationID" validate:"required"`
	SourceID              string      `json:"sourceID" validate:"required"`
	SessionType           int32       `json:"sessionType" validate:"required"`
	ClientMsgID           string      `json:"clientMsgID" validate:"required"`
	IsExternalExtensions  bool        `json:"isExternalExtensions"`
	MsgFirstModifyTime    int64       `json:"msgFirstModifyTime" validate:"required"`
	ReactionExtensionList []*KeyValue `json:"reactionExtensionList" validate:"required"`
}

type DeleteMessageReactionExtensionsResponse struct {
	CommResp
}

type MsgDeleteNotificationElem struct {
	GroupID     string   `json:"groupID"`
	IsAllDelete bool     `json:"isAllDelete"`
	SeqList     []uint32 `json:"seqList"`
}
